//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.12 at 06:39:36 PM BRST 
//


package de.kowohl.mpeg.mpeg7._2004;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TextualType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TextualType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;urn:mpeg:mpeg7:schema:2004>TextualBaseType">
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TextualType")
@XmlSeeAlso({
    CreationPreferencesType.Keyword.class,
    OrganizationType.Name.class,
    SummaryPreferencesType.SummaryTheme.class,
    KeywordAnnotationType.Keyword.class,
    SourcePreferencesType.DisseminationSource.class,
    SummaryThemeListType.SummaryTheme.class,
    PersonGroupType.Name.class,
    TermDefinitionBaseType.Name.class,
    SubjectTermDefinitionType.Note.class,
    InlineTermDefinitionType.Name.class,
    ClassificationPreferencesType.Subject.class,
    ClassificationPreferencesType.AssociatedData.class
})
public class TextualType
    extends TextualBaseType
{


}
