//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.12 at 06:12:40 PM BRST 
//


package de.origindd.mpeg.mpegv.cidl;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

import de.origindd.mpeg.mpeg21.TerminalCapabilityBaseType;
import de.origindd.mpeg.mpegv.scdv.AccelerationSensorCapabilityType;
import de.origindd.mpeg.mpegv.scdv.AmbientNoiseSensorCapabilityType;
import de.origindd.mpeg.mpegv.scdv.AngularAccelerationSensorCapabilityType;
import de.origindd.mpeg.mpegv.scdv.AngularVelocitySensorCapabilityType;
import de.origindd.mpeg.mpegv.scdv.AtmosphericPressureSensorCapabilityType;
import de.origindd.mpeg.mpegv.scdv.DistanceSensorCapabilityType;
import de.origindd.mpeg.mpegv.scdv.ForceSensorCapabilityType;
import de.origindd.mpeg.mpegv.scdv.HumiditySensorCapabilityType;
import de.origindd.mpeg.mpegv.scdv.IntelligentCameraCapabilityType;
import de.origindd.mpeg.mpegv.scdv.LightSensorCapabilityType;
import de.origindd.mpeg.mpegv.scdv.MotionSensorCapabilityType;
import de.origindd.mpeg.mpegv.scdv.OrientationSensorCapabilityType;
import de.origindd.mpeg.mpegv.scdv.PositionSensorCapabilityType;
import de.origindd.mpeg.mpegv.scdv.PressureSensorCapabilityType;
import de.origindd.mpeg.mpegv.scdv.TemperatureSensorCapabilityType;
import de.origindd.mpeg.mpegv.scdv.TorqueSensorCapabilityType;
import de.origindd.mpeg.mpegv.scdv.VelocitySensorCapabilityType;


/**
 * <p>Java class for SensorCapabilityBaseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SensorCapabilityBaseType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:mpeg:mpeg21:2003:01-DIA-NS}TerminalCapabilityBaseType">
 *       &lt;sequence>
 *         &lt;element name="Accuracy" type="{urn:mpeg:mpeg-v:2010:01-CIDL-NS}AccuracyType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{urn:mpeg:mpeg-v:2010:01-CIDL-NS}sensorCapabilityBaseAttributes"/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SensorCapabilityBaseType", propOrder = {
    "accuracy"
})
@XmlSeeAlso({
    LightSensorCapabilityType.class,
    OrientationSensorCapabilityType.class,
    HumiditySensorCapabilityType.class,
    AmbientNoiseSensorCapabilityType.class,
    DistanceSensorCapabilityType.class,
    AtmosphericPressureSensorCapabilityType.class,
    AngularVelocitySensorCapabilityType.class,
    TorqueSensorCapabilityType.class,
    VelocitySensorCapabilityType.class,
    TemperatureSensorCapabilityType.class,
    PositionSensorCapabilityType.class,
    IntelligentCameraCapabilityType.class,
    PressureSensorCapabilityType.class,
    AccelerationSensorCapabilityType.class,
    AngularAccelerationSensorCapabilityType.class,
    ForceSensorCapabilityType.class,
    MotionSensorCapabilityType.class
})
public abstract class SensorCapabilityBaseType
    extends TerminalCapabilityBaseType
{

    @XmlElement(name = "Accuracy")
    protected AccuracyType accuracy;
    @XmlAttribute(name = "unit")
    protected String unit;
    @XmlAttribute(name = "maxValue")
    protected Float maxValue;
    @XmlAttribute(name = "minValue")
    protected Float minValue;
    @XmlAttribute(name = "offset")
    protected Float offset;
    @XmlAttribute(name = "numOfLevels")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger numOfLevels;
    @XmlAttribute(name = "sensitivity")
    protected Float sensitivity;
    @XmlAttribute(name = "SNR")
    protected Float snr;

    /**
     * Gets the value of the accuracy property.
     * 
     * @return
     *     possible object is
     *     {@link AccuracyType }
     *     
     */
    public AccuracyType getAccuracy() {
        return accuracy;
    }

    /**
     * Sets the value of the accuracy property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccuracyType }
     *     
     */
    public void setAccuracy(AccuracyType value) {
        this.accuracy = value;
    }

    /**
     * Gets the value of the unit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnit() {
        return unit;
    }

    /**
     * Sets the value of the unit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnit(String value) {
        this.unit = value;
    }

    /**
     * Gets the value of the maxValue property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getMaxValue() {
        return maxValue;
    }

    /**
     * Sets the value of the maxValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setMaxValue(Float value) {
        this.maxValue = value;
    }

    /**
     * Gets the value of the minValue property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getMinValue() {
        return minValue;
    }

    /**
     * Sets the value of the minValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setMinValue(Float value) {
        this.minValue = value;
    }

    /**
     * Gets the value of the offset property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getOffset() {
        return offset;
    }

    /**
     * Sets the value of the offset property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setOffset(Float value) {
        this.offset = value;
    }

    /**
     * Gets the value of the numOfLevels property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumOfLevels() {
        return numOfLevels;
    }

    /**
     * Sets the value of the numOfLevels property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumOfLevels(BigInteger value) {
        this.numOfLevels = value;
    }

    /**
     * Gets the value of the sensitivity property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getSensitivity() {
        return sensitivity;
    }

    /**
     * Sets the value of the sensitivity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setSensitivity(Float value) {
        this.sensitivity = value;
    }

    /**
     * Gets the value of the snr property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getSNR() {
        return snr;
    }

    /**
     * Sets the value of the snr property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setSNR(Float value) {
        this.snr = value;
    }

}
